apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: latest
    chart: rabbitmq
    helm:
      values: |
        replicaCount: 2
        persistence:
          enabled: true
          size: 1Gi
        auth:
          username: "admin"
          password: "rabbitmq-password"
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

