apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/yourusername/k8s-deployments.git"  # Change to your repo
    targetRevision: main
    path: rabbitmq  # The folder containing the manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

